### ISSUE TITLE
Кнопка Запустить не становится активной

### ISSUE THREAD

**Issue by sanyasanev** [megazazik/yandex-tank-web#36]
Добрый день!
пробую развернуть у себя web интерфейс из этого проекта, для Yandex Tank.
Кнопка "Запустить" не становится активной. (скрин)
![image](https://github.com/megazazik/yandex-tank-web/assets/80787502/27ffcc08-d006-49ba-9b91-3e8cb96a0587)

Устанавливаю:
1. git https://github.com/megazazik/yandex-tank-web.git
2. из корневой папки проекта: "docker build -t qwe/tank ." 

Запускаю:
1. docker run -d -p 4000:4000 tank
2. перехожу браузером на localhost:4000
3. прохожу создание групп тестов
4. копирую yaml из файла в run-tank-config/load.yaml, и вставляю в поле "Enter phantom configuration:"

В "result phantom config:" выглядит как распарсилось успешно, но кнопка не становится активной. Пробовал копировать конфиги: весь файл yaml, только конфиг фантома, включая удаление лишней строки phantom, и выравнивание отступов.

В чём может быть проблема? 
может у Вас есть минимально работающий конфиг, который я мог бы использовать как пример?

**Comment by sanyasanev** [comment]
ещё актуально)

**Comment by megazazik** [comment]
Я впервые за несколько лет открыл этот проект в IDE и сразу увидел не закоммиченные изменения, которые по идее фиксят проблему с неактивной кнопкой. Закоммитил.

Но насколько весь остальной код в рабочем состоянии, сейчас уже сложно сказать.
Вероятнее всего он не заработает. Я точно не доделал все, что хотел, но на каком состоянии остановился, не помню.

Я не вижу по коду, чтобы конфиг для запуска теста каким-то образом передавался в yandex-tank. Скорее всего это и не было реализовано.

И также там были особенности запуска.
Во-первых, перед запуском приложения надо было запустить influxdb с помощью этой команды
https://github.com/megazazik/yandex-tank-web/blob/master/db/run

Во-вторых, базовый образ с yandex-tank был не актуальный и приходилось вручную собирать свой образ танка из исходников.
https://github.com/yandex/yandex-tank/issues/787
кажется, с помощью этого файла
https://github.com/yandex/yandex-tank/blob/master/docker/Dockerfile
а потом указывать этот базовый образ при сборке образа приложения.
Именно поэтому в сборке указано `--build-arg IMAGE=my-tank`
https://github.com/megazazik/yandex-tank-web/blob/master/package.json#L13

В общем состояние у проекта довольно сырое, скорее всего кому-то со стороны будет довольно сложно его запустить. А у меня планов по его доработке не было в обозримом будущем.

**Comment by sanyasanev** [comment]
хорошо, спасибо за детальное разъяснение!
всего хорошего!)
